export const TAG_LABEL: Record<string, string> = {
  underdeveloped: '展开不足/字数不够',
  chinglish: '中式表达',
  task_response_weak: '任务回应不足',
  coherence_weak: '逻辑连贯弱',
  grammar_weak: '语法薄弱',
  vocab_gap: '词汇空白',
  pronunciation_weak: '发音待提升',
  filler_heavy: '填充词过多',
  careless: '粗心',
  logic_misread: '逻辑误解',
  time_pressure: '时间不够',
  trap_distractor: '陷阱选项',
  grammar: '语法错误',
  preposition: '介词错误',
  collocation: '搭配错误',
  spelling: '拼写错误',
  word_choice: '用词不当',
  sentence_pattern: '句式问题',
}
